# Generated by Django 5.2.1 on 2025-06-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_type',
            field=models.CharField(default='yoga', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='instructor',
            field=models.CharField(default='yoga', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
