# Generated by Django 5.2.1 on 2025-06-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_attendance_class_type_attendance_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_type',
            field=models.CharField(default='yoga', max_length=50),
        ),
    ]
