# Generated by Django 5.2.1 on 2025-08-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_attendance_status_attendance_is_present'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'class_type')},
        ),
    ]
